export const PERMISSIONS = [
  "dashboard.view",
  "goals.view",
  "goals.manage",
  "leads.view",
  "leads.view_all",
  "leads.view_assigned",
  "leads.manage",
  "leads.edit_all",
  "leads.edit_assigned",
  "leads.assign",
  "leads.campaigns.manage",
  "leads.research.manage",
  "prospects.view_own",
  "prospects.view_all",
  "prospects.manage_own",
  "prospects.manage_all",
  "calls.view_own",
  "calls.view_all",
  "calls.create",
  "calls.operate_assigned",
  "callbacks.view_all",
  "callbacks.view_own",
  "callbacks.manage_all",
  "callbacks.manage_own",
  "outreach.create",
  "outreach.view_own",
  "outreach.view_all",
  "followups.view_own",
  "followups.view_all",
  "followups.manage_own",
  "followups.manage_all",
  "appointments.view_own",
  "appointments.view_all",
  "appointments.manage_own",
  "appointments.manage_all",
  "pipeline.view_own",
  "pipeline.view_all",
  "pipeline.manage",
  "opportunities.manage_own",
  "opportunities.manage_all",
  "sales.goals.view_own",
  "sales.goals.view_all",
  "sales.goals.manage",
  "sales.reports.view",
  "analytics.company",
  "analytics.personal",
  "financials.view",
  "suppression.manage",
  "settings.manage",
  "users.manage",
  "exports.full",
  "locks.manage",
  "calling.policy.manage",
  "owner_reach.review",
  "push.manage_own",
  "clients.view",
  "clients.manage",
  "revenue.view",
  "revenue.manage",
  "revenue.goals.manage",
  "revenue.contracts.manage",
  "revenue.invoices.manage",
  "revenue.payments.manage",
  "revenue.forecasts.view",
  "revenue.forecasts.manage",
  "services.view",
  "services.manage",
  "team.view",
  "team.manage",
  "roles.manage",
  "integrations.manage",
  "organization.manage",
  "audit.view",
  "agents.view",
  "agents.manage"
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const permissionDescriptions: Record<PermissionKey, string> = {
  "dashboard.view": "View the organization command center.",
  "goals.view": "View revenue and operating goals.",
  "goals.manage": "Create and update revenue and operating goals.",
  "leads.view": "View lead records.",
  "leads.view_all": "View all organization lead records.",
  "leads.view_assigned": "View assigned lead records.",
  "leads.manage": "Create and update lead records.",
  "leads.edit_all": "Edit all organization lead records.",
  "leads.edit_assigned": "Edit assigned lead records.",
  "leads.assign": "Assign and reassign lead records.",
  "leads.campaigns.manage": "Create, launch, pause, and archive lead campaigns.",
  "leads.research.manage": "Run lead research, scoring, and classification jobs.",
  "prospects.view_own": "View assigned prospect records.",
  "prospects.view_all": "View all organization prospect records.",
  "prospects.manage_own": "Update assigned prospect records.",
  "prospects.manage_all": "Update all organization prospect records.",
  "calls.view_own": "View personal call activity.",
  "calls.view_all": "View call activity for the organization.",
  "calls.create": "Create manual call sessions and call attempts.",
  "calls.operate_assigned": "Operate assigned leads from the call desk.",
  "callbacks.view_all": "View all callback records.",
  "callbacks.view_own": "View assigned callback records.",
  "callbacks.manage_all": "Create, reschedule, complete, and cancel all callback records.",
  "callbacks.manage_own": "Create, reschedule, complete, and cancel assigned callback records.",
  "outreach.create": "Record outreach attempts.",
  "outreach.view_own": "View personal outreach attempts.",
  "outreach.view_all": "View all organization outreach attempts.",
  "followups.view_own": "View assigned follow-ups.",
  "followups.view_all": "View all organization follow-ups.",
  "followups.manage_own": "Create and complete assigned follow-ups.",
  "followups.manage_all": "Create and complete all organization follow-ups.",
  "appointments.view_own": "View assigned appointments.",
  "appointments.view_all": "View all organization appointments.",
  "appointments.manage_own": "Create and update assigned appointments.",
  "appointments.manage_all": "Create and update all organization appointments.",
  "pipeline.view_own": "View owned sales pipeline records.",
  "pipeline.view_all": "View organization-wide sales pipeline records.",
  "pipeline.manage": "Manage pipeline stages and organization-wide pipeline movement.",
  "opportunities.manage_own": "Create and update owned opportunities.",
  "opportunities.manage_all": "Create and update all organization opportunities.",
  "sales.goals.view_own": "View personal sales goals.",
  "sales.goals.view_all": "View organization sales goals.",
  "sales.goals.manage": "Create and update sales goals.",
  "sales.reports.view": "View organization sales reports.",
  "analytics.company": "View company-wide sales analytics.",
  "analytics.personal": "View personal sales analytics.",
  "financials.view": "View financial operating data.",
  "suppression.manage": "Review and override suppression records.",
  "settings.manage": "Manage application settings.",
  "users.manage": "Manage users and memberships.",
  "exports.full": "Export full organization datasets.",
  "locks.manage": "Review and release stale lead locks.",
  "calling.policy.manage": "Manage calling hours and queue policy.",
  "owner_reach.review": "Review and override Owner Reach Score explanations.",
  "push.manage_own": "Manage personal push notification subscriptions.",
  "clients.view": "View client records.",
  "clients.manage": "Create and update client records.",
  "revenue.view": "View organization revenue surfaces.",
  "revenue.manage": "Manage organization revenue records.",
  "revenue.goals.manage": "Create and update revenue goals.",
  "revenue.contracts.manage": "Create and update revenue contracts.",
  "revenue.invoices.manage": "Create and update revenue invoices.",
  "revenue.payments.manage": "Record and adjust revenue payments.",
  "revenue.forecasts.view": "View revenue forecast snapshots.",
  "revenue.forecasts.manage": "Create revenue forecast snapshots.",
  "services.view": "View service offerings.",
  "services.manage": "Create and update service offerings.",
  "team.view": "View team members.",
  "team.manage": "Invite and manage team members.",
  "roles.manage": "Manage roles and permissions.",
  "integrations.manage": "Manage organization integrations.",
  "organization.manage": "Manage organization settings and branding.",
  "audit.view": "View security and audit events.",
  "agents.view": "View agent workspace shells.",
  "agents.manage": "Manage agent configuration."
};

export const founderPermissions = [...PERMISSIONS];

export const salespersonPermissions: PermissionKey[] = [
  "dashboard.view",
  "leads.view",
  "leads.view_assigned",
  "leads.manage",
  "leads.edit_assigned",
  "prospects.view_own",
  "prospects.manage_own",
  "calls.create",
  "calls.operate_assigned",
  "outreach.create",
  "outreach.view_own",
  "callbacks.view_own",
  "callbacks.manage_own",
  "followups.view_own",
  "followups.manage_own",
  "appointments.view_own",
  "appointments.manage_own",
  "calls.view_own",
  "pipeline.view_own",
  "opportunities.manage_own",
  "sales.goals.view_own",
  "analytics.personal",
  "push.manage_own",
  "clients.view",
  "agents.view"
];

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSIONS as readonly string[]).includes(value);
}
